#########################################################################
#                                                                       #
#  Copyright 1996, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	mod/nemesis/tasks
# 
# DESCRIPTION:
#
#	
#

ROOT	= ../../..

MODULE		= tasks

CFILES		= $(wildcard *.c)

include $(ROOT)/mk/rules.mk

