#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	net/TFTP
# 
# DESCRIPTION:
#
#	TFTP implementation
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:19:49 +0000 dr10009 $
#

ROOT	= ../../..

MODULE	= TFTP

EXTRA_OBJDIR = $(ROOT)/lib/static/socket
EXTRA_OBJS = libsocket.a

CFILES	  = $(wildcard *.c)

include $(ROOT)/mk/rules.mk

