#########################################################################
#                                                                       #
#  Copyright 1997, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	mod/nemesis/ugdb
# 
# DESCRIPTION:
#
#	User space impl of gdb. 
#

ROOT	= ../../..

MODULE		= ugdb

CFILES		= ugdb.c stub_$(ARCH).c

include $(ROOT)/mk/rules.mk

