ROOT	= .

SUBDIRS	= middlc middl2tex nsplitd genoffsets cl astgen udptelnet mkfs.simplefs

SUBDIRS_alpha_osf1_3.2 = alphabuild nembuild
SUBDIRS_hp700_hpux_A.09.05 = nembuild
SUBDIRS_ix86_linux_rh4.0 = nembuild intelbuild multiboot-fixup
SUBDIRS_ix86_linux_rh5.0 = nembuild intelbuild multiboot-fixup
SUBDIRS_ix86_linux_rh5.1 = nembuild intelbuild multiboot-fixup
SUBDIRS_ix86_linux_rh3.0.3 = nembuild intelbuild multiboot-fixup
SUBDIRS_ix86_linux_sl3 = nembuild intelbuild multiboot-fixup
SUBDIRS_mips_ultrix_4.3 = undefarm

include $(ROOT)/mk/rules.mk
