#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#      dev/pci/s3/xrip/s3
# 
# DESCRIPTION:
#
#      XF86 s3 code
# 
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:18:52 +0000 dr10009 $
# 

ROOT = ../../../../..

LOCAL_INC = -I ../h  -I ../commonhw -I ../hnull
CFILES = ${wildcard *.c}

LDLUMP = s3lump.o

include $(ROOT)/mk/rules.mk
