#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	lib/intmath
# 
# DESCRIPTION:
#
#	
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:16:19 +0000 dr10009 $
#

ROOT	= ../../..

SUBDIRS_alpha	= alpha
SUBDIRS_mips	= mips
SUBDIRS_arm	= arm
SUBDIRS_ix86	= ix86


include $(ROOT)/mk/rules.mk

