#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	lib/c/stdio
# 
# DESCRIPTION:
#
#	
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:16:19 +0000 dr10009 $
#

ROOT	= ../../../..

#LOCAL_DEF	= -DPRINTF_DOMAIN_IDS

LDLUMP		= stdio
CFILES		= $(wildcard *.c)

LOCAL_OBJS = ../../../../lib/static/debug/libdebug.a

include $(ROOT)/mk/rules.mk

