#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#      mod/fs/ramdisk
# 
# DESCRIPTION:
#
#      Ramdisk implementation
# 
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:19:15 +0000 dr10009 $
# 


ROOT = ../../..

MODULE = ramdisk

CFILES = ramdisk.c

include $(ROOT)/mk/rules.mk
