#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	./net
# 
# DESCRIPTION:
#
#	
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:19:49 +0000 dr10009 $
#

ROOT	= ../../..

SUBDIRS	= 

CFILES	= netif.c pool.c

INTERFACES = FragPool.if

MODULE	= netif

include $(ROOT)/mk/rules.mk

clean:: 
	$(RM) *.ast typecodes.map

