#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	net/sunrpc/h/rpc
# 
# DESCRIPTION:
#
#	sunrpc implementation
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:19:49 +0000 dr10009 $
#

ROOT	= ../../../../..

include $(ROOT)/mk/rules.mk

