#########################################################################
#                                                                       #
#  Copyright 1996, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	./net/Protos/IPV6
# 
# DESCRIPTION:
#
#	Ho ho ho. Noddy impl. of IP v6 within nemesis.
#

ROOT	= ../../../..

MODULE	= IPV6

CFILES	= $(wildcard *.c)

include $(ROOT)/mk/rules.mk

