#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	dev/pci/mga/common_hw
# 
# DESCRIPTION:
#
#	Device driver for PMAGBBA framestore
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:18:52 +0000 dr10009 $
#


ROOT = ../../../..

CFILES = ${wildcard *.c}

LDLUMP = common_hw.o

include $(ROOT)/mk/rules.mk

