#########################################################################
#                                                                       #
#  Copyright 1997, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	mod/nemesis/threads
# 
# DESCRIPTION:
#
#	
#
#

ROOT	= ../../..

MODULE		= threads

CFILES		= $(wildcard *.c)
ASFILES_mips	= thead_mips.S
ASFILES_alpha	= thead_alpha.S
ASFILES_arm	= thead_arm.S
ASFILES_intel	= thead_intel.S
ASFILES_intel-smp	= thead_intel-smp.S

include $(ROOT)/mk/rules.mk

