#########################################################################
#                                                                       #
#  Copyright 1996, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	lib/veneer/c
# 
# DESCRIPTION:
#
#	Placeholder
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:16:19 +0000 dr10009 $
#

ROOT	= ../../..

SUBDIRS		= 


VENEER = libc

include $(ROOT)/mk/rules.mk

