#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#      dev/pci/s3/xrip/hc
# 
# DESCRIPTION:
#
#      Header files for xrip
# 
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:18:52 +0000 dr10009 $
# 

ROOT	= ../../../../..

LDLUMP		= HC.o

CFILES		= $(wildcard *.c)

LOCAL_INC = -I ../h -I ../hnull



include $(ROOT)/mk/rules.mk

