#!/bin/sh
while [ $# -gt 0 ]; do
  (
    test -f "$1" || { echo "$1: No such file or directory" 1>&2; exit 1; }
    { cp $1 cln$$ && rm $1 && mv cln$$ $1; } || { rm -f cln$$; exit 1; }
  )
  shift
done
