#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#      dev/pci/s3/xrip
# 
# DESCRIPTION:
#
#      Xrip
# 
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:18:52 +0000 dr10009 $
# 

ROOT = ../../../..
SUBDIRS = hnull h s3 commonhw hc
LOCAL_INC = -I ./h

CFILES = ${wildcard *.c}

LDLUMP = xripbase.o

include $(ROOT)/mk/rules.mk



