#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	./app/rawvideo
# 
# DESCRIPTION:
#
#	
#
# ID : $Id: Makefile 1.1 Tue, 20 Apr 1999 17:20:31 +0100 dr10009 $
#

ROOT	= ../..

CFILES = $(wildcard *.c)
PERSONALITY_LIBS = $(ROOT)/lib/static/posix/libposix.a

PROGRAM		= rvideo

include $(ROOT)/mk/rules.mk

