#########################################################################
#                                                                       #
#  Copyright 1994, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	lib/exec
# 
# DESCRIPTION:
#
#	Implements Exec.if
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:16:19 +0000 dr10009 $
#

ROOT	= ../..

MODULE	= binloader

CFILES	= exec.c 
CFILES_ix86 = load_ix86.c
CFILES_alpha= relocate_alpha.c load_alpha.c	# ecoff stuff.


include $(ROOT)/mk/rules.mk

