
#########################################################################
#                                                                       #
#  Copyright 1998, University of Cambridge Computer Laboratory  	#
#                                                                       #
#  All Rights Reserved.						        #
#                                                                       #
#########################################################################
#
# DIRECTORY:
#
#	./links
# 
# DESCRIPTION:
#
#	Links repository
#
# ID : $Id: Makefile 1.1 Thu, 18 Feb 1999 14:16:19 +0000 dr10009 $
#

ROOT = ..

include $(ROOT)/mk/rules.mk

all:: 
	PYTHONPATH=$(ROOT)/glue python ../glue/geninstalllinks.py
