# nemmaster gendetails
#
# Copyright 1998 Dickon Reed
#
# Generate a string recording who generated a file

import os, socket, pwd, time

def gendetails():
    (uid,_,_,_,gcos,_,_) = pwd.getpwuid(os.getuid())
    return ' by '+uid+'('+gcos+')' + ' on '+socket.gethostname()
    # XXX; do *not* write the date in to autogenerated files, as this
    # causes the file to change every time geninfrastructure happens,
    # which causes the entire tree to rebuild ;-)
    #+ ' at '+time.ctime( time.time() )


